export const IS_LOADING = 'IS_LOADING';
export const CHANGE_DEVICE = "CHANGE_DEVICE";

export const RESULTS_LOADED = 'RESULTS_LOADED';
export const CURRENCIES_LOADED = 'CURRENCIES_LOADED';
export const LOCALES_LOADED = 'LOCALES_LOADED';
export const MARKETS_LOADED = 'MARKETS_LOADED';

export const SET_LOCATION_SUCCESS = 'SET_LOCATION_SUCCESS';
export const SET_CURRENCY = 'SET_CURRENCY';
export const SET_LOCALE = 'SET_LOCALE';
export const SET_MARKET = 'SET_MARKET';