export const IS_LOADING = 'IS_LOADING';
export const CHANGE_DEVICE = "CHANGE_DEVICE";

export const RESULTS_LOADED = 'RESULTS_LOADED';
export const DEPARTURE_SUGGESTIONS_LOADED = 'DEPARTURE_SUGGESTIONS_LOADED';
export const ARRIVAL_SUGGESTIONS_LOADED = 'ARRIVAL_SUGGESTIONS_LOADED';
export const CURRENCIES_LOADED = 'CURRENCIES_LOADED';
export const LOCALES_LOADED = 'LOCALES_LOADED';
export const MARKETS_LOADED = 'MARKETS_LOADED';

export const CHANGE_DEPARTURE = 'CHANGE_DEPARTURE';
export const CHANGE_ARRIVAL = 'CHANGE_ARRIVAL';
export const CHANGE_MAXSTOPS = 'CHANGE_MAXSTOPS';
export const CHANGE_ADULTS = 'CHANGE_ADULTS';
export const CHANGE_CHILDREN = 'CHANGE_CHILDREN';
export const CHANGE_TRIPTYPE = 'CHANGE_TRIPTYPE';
export const CHANGE_FROM_DATE = 'CHANGE_FROM_DATE';
export const CHANGE_TO_DATE = 'CHANGE_TO_DATE';

export const SET_LOCATION_SUCCESS = 'SET_LOCATION_SUCCESS';
export const SET_CURRENCY = 'SET_CURRENCY';
export const SET_LOCALE = 'SET_LOCALE';
export const SET_MARKET = 'SET_MARKET';